### ISSUE TITLE
Improvement : Better youtube-dl check

### ISSUE THREAD

**Issue by azlux** [MrKulu/Jukebox#1]
Hi,
you check if the time is above 3600 to know if your music is downloaded before sending a error message.
You can use the subprocess stdout to know the state of youtube-dl :  subprocess.call(args, *, stdin=None, stdout=None, stderr=None, shell=False)
I think you can avoid error like that.

**Comment by MrKulu** [comment]
Hi,
Thank you for your suggestion, it will be implemented soon.
