### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by azlux** [MrKulu/Jukebox#2]
Since few days, the python3 version of pymumble is available : https://github.com/azlux/pymumble/tree/pymumble_py3 .
I think it's better to code with py3 than py2. The code still on beta and but I think everything is ready.
Az

**Comment by MrKulu** [comment]
Thanks, I will look into it.

**Comment by azlux** [comment]
And with this version you can use the fonction : 

```
self.mumble.set_codec_profile("audio")
```

To have a better sound !

**Comment by MrKulu** [comment]
Sounds great, I have to try it out
